# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiteSmile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiteSmile
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'LiteSmileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LiteSmile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LiteSmile-tvOS

  target 'LiteSmile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
